version: '3'
services:
  group-site:
    image: mysql:8.0
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: database
      MYSQL_USER: fwx
      MYSQL_PASSWORD: mypassword
    volumes:
      - ./data:/tmp/mysql
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 5s
      retries: 3
